// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdcptxpgccygorswylmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkY3B0eHBnY2N5Z29yc3d5bG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MTY1OTgsImV4cCI6MjA2ODE5MjU5OH0.Wl4ManE69koEa-k-UoQ86xXCVRtXO1xikaNI4mJ7PgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});